### PR TITLE
Closes #134: inventory dashboard

### LINKED ISSUE #134: D&T Inventory Dashboard Page
This is the page where users can manage participants, send reminders, adjust the inventory schedule, add/view learning questions (and edit their own), and view the report. 

Remember that the Learning Questions will be in a modal rather than the sidebar. @HeyCat, do you have a design that shows the Learning Questions button with the others?

### PR DESCRIPTION
**Pull request by MakotoTheKnight**
This PR is good to go.  Notes:

 - This follows the style defined in #134 with noted deviations in the listing of learning questions and font styles.
 - There are a lot of styles here that would need to change - notably, the card indicating who has been invited to participate - but I get the impression that this is a more global change than can be contained in the scope of this task.  This also applies to the color of the modal buttons (participant management and sending reminders).
 - The "Modify Schedule" button was not clearly specified and does not function.
 - "Go to Report" does not function due to the page not existing yet.
 - All other buttons on the page should function.

### CODE REVIEW

**Comment by bithavoc** [comment]
Are we supposed to include a link to the dashboard from the inventory entry in this PR?



As an example, this is how the assessment looks like now.

**Comment by MakotoTheKnight** [comment]
No.  That's to be covered by #192.

**Comment by bithavoc** [comment]
@MakotoTheKnight when I read
> All other buttons on the page should function.

does this means that Add New Participant, Manage Permissions and Invite new participants is supposed to work?

**Comment by MakotoTheKnight** [comment]
@bithavoc:  Yes, those buttons should function.

**Comment by bithavoc** [comment]
`Invite new participant` triggers the modal titled `Add New Participant` but when I press `Add to District` no action seems to take place, the console reports `POST http://localhost:7130/v1/inventories/invitations 404 (Not Found)`.

**Comment by bithavoc** [comment]
When I press `Add new Participant` a dialog titled `Inventory Participants` pops up, however, the list is empty even when my inventory has participants in it. console reports `GET http://localhost:7130/v1/inventories/2/participants/all 403 Forbidden`

**Comment by MakotoTheKnight** [comment]
@bithavoc:  Could I get you to take another look at this?

**Comment by bithavoc** [comment]
When I press `Invite new participant` a dialog titled `Add new participant` pops up, I filled the contact information but I get `POST http://localhost:7130/v1/inventories/1/invitations 403 Forbidden`

**Comment by bithavoc** [comment]
When I try to send a message, I get `POST http://localhost:7130/v1/inventories/1/reminders 401 Forbidden`

**Comment by bithavoc** [comment]
List of participants does not refresh when a new participant is invited. Same with Add participant from inventory.

**Comment by MakotoTheKnight** [comment]
I'll rebase this against what we have in staging soon so that bug no longer appears @bithavoc.

**Comment by MakotoTheKnight** [comment]
@bithavoc Go ahead and give this another look.  One of the other missing components was that, on this page specifically, when you invite a participant, that email needs to be sent immediately.

**Comment by bithavoc** [comment]
LGTM :shipit:

**Pull request merged**
