### PR TITLE
Closes #209: make product name required

### LINKED ISSUE #209: product_name of a product entry's general inventory question should be required
see #165

### PR DESCRIPTION
**Pull request by juliosantos**

### CODE REVIEW

**Comment by juliosantos** [comment]
Closes #209

**Comment by bithavoc** [comment]
I noticed that in [data set name validation](https://github.com/MobilityLabs/pdredesign-server/pull/241) even when the Data Set Name field is not visible(I scrolled down to reach the Save button), the HTML5 error message shows up in the top of the screen and I'm able to see I'm missing the data set name so I scroll up and fill the field. For some reason this is not happening for Product Name, the Save button doesn't process the form but there is no visible hint of what am I missing in the form.

**Comment by juliosantos** [comment]
@bithavoc Well spotted. Should be fixed now. Over to you :)

**Comment by bithavoc** [comment]
LGTM :shipit:

**Pull request merged**
