### PR TITLE
Closes #161: fix participants listing

### LINKED ISSUE #161: Adding New Participants/Facilitators

### PR DESCRIPTION
**Pull request by MakotoTheKnight**
This PR is good to go. 

 - This fixes an issue in which we rely on the controller to give us the user; however, that user is defined to be the currently logged-in user and not the actual participants.

### CODE REVIEW

**Comment by MakotoTheKnight** [comment]
@bithavoc:  Mind taking a quick glance at this?

**Comment by bithavoc** [comment]
@MakotoTheKnight can you give me some instructions to test this? I can't really see where we use it

**Comment by MakotoTheKnight** [comment]
Sure.  When creating a new assessment, or modifying an existing but not yet started assessment, click on "Add New Participants".  Add different participants to the assessment to ensure that their name and email appear instead of just the person that's logged in.

**Comment by bithavoc** [comment]
LGTM

**Pull request merged**
