### PR TITLE
#179 #183 Inventory products list

### LINKED ISSUE #179: Edit Inventory Page: Product Listing
Wire in the product listing.

 - Add filters and search bar
 - Add product listing (including information for product name, vendor, and "used for")

### LINKED ISSUE #183: Create /inventories/:id/products resource
For tasks #179 and #165, we require an endpoint to pull back a listing of product entries.

Data returned should be:

 - id
 - title
 - vendor
 - purpose (correlates to "Used for")
 - hosting (correlates to "Where is the data hosted?")
 - attached_to_other_products (boolean field)
 - single_sign_on
 - usage (represents staff usage)

### PR DESCRIPTION
**Pull request by bithavoc**
Closes #179
Closes #183

### CODE REVIEW

**Comment by juliosantos** [comment]
This PR is included in https://github.com/MobilityLabs/pdredesign-server/pull/206, right? My comments there should apply here too.

**Comment by MakotoTheKnight** [comment]
If the screen's just the right size, we could run into this bleeding over the edge:

image

I'd recommend that we leverage some of Bootstrap's `table` classes.

**Comment by bithavoc** [comment]
@MakotoTheKnight added the responsive style to the table, it worked.

as for the sidebar buttons, we can solve this by incrementing the size of the sidebar in `app/views/pdr_client/layouts/application.html.erb`:

from `col-md-9` to `col-md-8`
and `col-md-3` to `col-md-4`.



thoughts?

**Comment by bithavoc** [comment]
@MakotoTheKnight @juliosantos please take another look at this PR

**Comment by MakotoTheKnight** [comment]
We're still missing an empty state here:

image

I would imagine that we'd want to prevent the user from hiding everything except the column we're searching on in this view.  @HeyCat:  thoughts on that?

**Comment by MakotoTheKnight** [comment]
Alright, this looks good to me.

I've played around a bit with the search and it seems that we can search on any column, which may cause some ambiguity for users searching for "Alpha Product" and having a vendor of their product actually being called "Al".

That, I'm not so bothered with.  We can roll out with this functionality.

:shipit:

**Pull request merged**
