### PR TITLE
Closes #240: add and require name for data entries

### LINKED ISSUE #240: Add name to Data Entry
- [x] Add name column to `data_entries` table
- [x] Update form to require name to be entered on data entries
- [x] Be sure name is required on product entries

### PR DESCRIPTION
**Pull request by juliosantos**

### CODE REVIEW

**Comment by bithavoc** [comment]
LGTM-rebase-required :shipit:

**Comment by juliosantos** [comment]
@bithavoc rebased

**Comment by bithavoc** [comment]
It looks like this one still has conflicts, maybe because we recently merged more stuff in staging.

**Comment by juliosantos** [comment]
@bithavoc all clean now here too

**Pull request merged**
